# Generated by Django 4.2.7 on 2024-02-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserLat', models.CharField(max_length=255)),
                ('UserLong', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Indirizzo', models.CharField(max_length=255)),
                ('Descrizione', models.TextField(max_length=500)),
                ('Latitudine', models.CharField(max_length=255)),
                ('Longitudine', models.CharField(max_length=255)),
                ('Sfida', models.TextField(max_length=300)),
                ('Immagine', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Percorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=255)),
            ],
        ),
    ]
