# Generated by Django 5.0.1 on 2024-02-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuoghiAttrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.TextField(max_length=100)),
                ('Descrizione', models.TextField(max_length=500)),
                ('Sfida', models.TextField(max_length=300)),
                ('Immagine', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Mappa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Luogo', models.CharField(max_length=50)),
                ('Latitudine', models.CharField(max_length=50)),
                ('Longitudine', models.CharField(max_length=50)),
            ],
        ),
    ]
