# Generated by Django 5.0 on 2024-01-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuoghiAttrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.TextField(max_length=100)),
                ('Descrizione', models.TextField(max_length=500)),
                ('Sfida', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='LuoghiAtrazione',
        ),
    ]
