# Generated by Django 5.0 on 2024-02-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappa',
            name='Immagine',
        ),
    ]
