# Generated by Django 5.0.1 on 2024-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappa',
            name='Latitudine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mappa',
            name='Longitudine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mappa',
            name='Luogo',
            field=models.CharField(max_length=255),
        ),
    ]
