# Generated by Django 4.2.7 on 2024-02-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_mappa_latitudine_alter_mappa_longitudine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luoghiattrazione',
            name='Descrizione',
            field=models.TextField(max_length=2500),
        ),
    ]
