# Generated by Django 4.2.7 on 2024-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_mappa'),
    ]

    operations = [
        migrations.AddField(
            model_name='luoghiattrazione',
            name='Immagine',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
