# Generated by Django 5.0 on 2024-01-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_appuser'),
        ('Api', '0004_luoghiattrazione_immagine'),
    ]

    operations = [
    ]
