# Generated by Django 5.0.1 on 2024-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_marker_delete_luoghiattrazione_delete_mappa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserLat', models.CharField(max_length=255)),
                ('UserLong', models.CharField(max_length=255)),
            ],
        ),
    ]
