# Generated by Django 5.0.1 on 2024-02-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='Descrizione',
            field=models.TextField(max_length=3000),
        ),
    ]
