# Generated by Django 4.2.7 on 2024-02-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_luoghiattrazione_descrizione'),
        ('Api', '0005_direction'),
    ]

    operations = [
    ]
