# Generated by Django 5.0 on 2024-01-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_merge_0004_appuser_0004_luoghiattrazione_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luoghiattrazione',
            name='Immagine',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
