# Generated by Django 5.0 on 2024-02-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_delete_appuser'),
        ('Api', '0006_remove_luoghiattrazione_immagine_delete_appuser'),
    ]

    operations = [
    ]
