# Generated by Django 5.0.1 on 2024-02-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_marker_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='Desbrev',
            field=models.TextField(default='', max_length=500),
        ),
    ]
