# Generated by Django 5.0.1 on 2024-02-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_luoghiattrazione_immagine_delete_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappa',
            name='Immagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
