# Generated by Django 5.0.1 on 2024-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_mappa_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappa',
            name='Immagine',
        ),
        migrations.AddField(
            model_name='luoghiattrazione',
            name='Immagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
