# Generated by Django 5.0 on 2024-03-17 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_marker_contatti_marker_costi_marker_orari'),
    ]

    operations = [
        migrations.AddField(
            model_name='percorso',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.marker'),
        ),
    ]
