# Generated by Django 4.2.6 on 2024-03-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
