# Generated by Django 5.0 on 2024-03-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_percorso_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percorso',
            name='marker',
        ),
        migrations.AddField(
            model_name='marker',
            name='percorso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='Api.percorso'),
        ),
    ]
