# Generated by Django 5.0.3 on 2024-03-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remove_percorso_marker_marker_percorso'),
        ('Api', '0012_profile_user_delete_customuser_profile_user'),
    ]

    operations = [
    ]
